### ISSUE TITLE
FRQ 1 Review

### ISSUE THREAD

**Issue by samayass** [samayass/samayaCSA#10]
Score: /3
**Implement FRQ1 in Spring project**
- [x] [AP Calendar](https://github.com/samayass/spring_portfolioT2/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/APCalendar.java)
- [x] [Year](https://github.com/samayass/spring_portfolioT2/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/Year.java)

**Enhance APIs and @RESTController to work with the all POJOs and APCalendar**
- [x] [Api Controller](https://github.com/samayass/spring_portfolioT2/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/CalendarApiController.java)

**Test APIs with Browser, Curl, or Postman. Illustrate or show tangibles**
- [x] isLeapYear
<img width="650" alt="isleapyear" src="https://user-images.githubusercontent.com/89225474/202651722-691d714e-7771-4194-b4ca-b94bd05bc67a.png">

- [x] firstDayOfYear

<img width="685" alt="first day of year" src="https://user-images.githubusercontent.com/89225474/202651875-9b949e04-24e4-4551-8319-92fb984110e0.png">

- [x] numberOfLeapYears

<img width="682" alt="numberofleapyears" src="https://user-images.githubusercontent.com/89225474/202651959-6820a522-39fe-4b12-aecf-a90015ee7a54.png">

- [x] dayOfYear

<img width="671" alt="dayofyear" src="https://user-images.githubusercontent.com/89225474/202652038-f7c68bf6-c650-4d5a-a86f-4224d4c6541e.png">

- [x] Debugger
<img width="759" alt="debug" src="https://user-images.githubusercontent.com/89225474/202652203-c265e968-fc45-4e10-95c8-7a040ecd0943.png">

**Comment by jm1021** [comment]
2.8
