### ISSUE TITLE
FRQ 2 Review

### ISSUE THREAD

**Issue by samayass** [samayass/samayaCSA#11]
# [Code](https://github.com/samayass/spring_portfolioT2/tree/master/src/main/java/com/nighthawk/spring_portfolio/mvc/person)
crossover grade: 2.7

## Build tester method (public static void main) for Person Pojo. Test zero argument and all argument constructor. build toString method to display attributes of the class.

<br>
tester
<img width="969" alt="tester" src="https://user-images.githubusercontent.com/89225474/204168283-991577a9-4adf-4aba-998d-6d72d1598ce6.png">
output
<img width="539" alt="outputtester" src="https://user-images.githubusercontent.com/89225474/204168342-548abd26-c37e-48ad-b08c-56c6bb2f0165.png">
<br>

## Build other attributes into POJO that where mentioned in project dialog at the beginning of this blog. Add 1 or more APIs. Use Issues to plan and track work.
<br>
algorithm
<img width="398" alt="bmi" src="https://user-images.githubusercontent.com/89225474/204168529-d3838e9e-fa3a-4e70-a38b-97d914d32bdb.png">
<img width="636" alt="step" src="https://user-images.githubusercontent.com/89225474/204168539-f553a7fe-3abb-4c41-a61f-1d871edd40df.png">
toString
<img width="301" alt="tostring" src="https://user-images.githubusercontent.com/89225474/204168545-aa205823-672f-4bc1-aee7-2f01d8b4b3c9.png">
Controller
<img width="392" alt="controller" src="https://user-images.githubusercontent.com/89225474/204168549-d68bd39a-ac12-4e93-abe5-51c01b063927.png">
Postman
<img width="838" alt="create" src="https://user-images.githubusercontent.com/89225474/204169098-50aba078-cddd-4a07-9edc-09c1a03b1e68.png">
<img width="836" alt="person" src="https://user-images.githubusercontent.com/89225474/204169107-327075d8-8927-4ae1-adde-5194f99c6d27.png">
<img width="839" alt="bmiapi" src="https://user-images.githubusercontent.com/89225474/204169112-e82192a0-a229-4224-8aa1-ac738c1ab7f2.png">
<img width="847" alt="stepapi" src="https://user-images.githubusercontent.com/89225474/204169118-0e42022b-8452-45f2-9b3e-3a8d7617cdc6.png">
<br>

## Correct the BUG in setStats! Currently, it won't let you do more than one date.
<img width="360" alt="code" src="https://user-images.githubusercontent.com/89225474/204195626-9a341d48-d583-4ceb-b32a-934f9d572fe3.png">
<img width="795" alt="setstats" src="https://user-images.githubusercontent.com/89225474/204195531-96a6b9c9-8212-4443-9de9-df063156279a.png">

**Comment by sarayu-pr11** [comment]
2.8/3
- meaningful screenshots showing all work completed
- BMI and Step Counter as extra
- very nice
