### ISSUE TITLE
Week 2: Using Objects

### ISSUE THREAD

**Issue by samayass** [samayass/samayaCSA#4]
# **[My Fastpages](https://samayass.github.io/samayaCSA/)**
**Score: 2.7+/3 - based on crossover grade**
**Score: 2.8/3 - based on review**

- [x] [Team Menu](https://sarayu-pr11.github.io/teamGrapeSnails/jupyter/2022/09/05/menu.html)
- [x] [Team Repo For Menu](https://github.com/sarayu-pr11/teamGrapeSnails)
- [x] [Code.org OOP](https://samayass.github.io/samayaCSA/markdown/2022/09/05/unit1-code-org.html)
- [x] [Team Tasks Blog](https://sarayu-pr11.github.io/teamGrapeSnails/markdown/2022/09/01/features.html)

**Comment by sarayu-pr11** [comment]
**2.7+/3 Graded By: Sarayu Pochimireddy**
Team Menu - went above and beyond for features and added successfully to menu: did 3 features
Team repo is set up and functional
Code.org takeaways are thorough and organized
Team tasks blog has good planning and organization
