### ISSUE TITLE
Week 3 - Backend Development

### ISSUE THREAD

**Issue by samayass** [samayass/samayaCSA#5]
# [**My Fastpages**](https://samayass.github.io/samayaCSA/)
**Score: 2.7/3 - based on crossover grade
Score: /3 - based on review**
- [x] [Focus / Habits](https://samayass.github.io/samayaCSA/markdown/2022/09/11/gratitude.html)
- [x] [Deployment on AWS](https://samayacsa.tk/)
- [x] [If Else Lesson](https://samayass.github.io/samayaCSA/jupyter/2022/09/11/ifs.html)

**Comment by sarayu-pr11** [comment]
**2.7/3 Graded by: Sarayu Pochimireddy**
Focus / Habits:  full credit, detailed takeaways and goals for future
Deployment on AWS: website deployed and functional
If Else Lesson: detailed exmaples for each statement and situation
