### ISSUE TITLE
Week 4 - Free Response Question No. 1

### ISSUE THREAD

**Issue by samayass** [samayass/samayaCSA#6]
# [**My Fastpages**](https://samayass.github.io/samayaCSA/)
**Score: 2.7+/3 - based on crossover grade
Score: 3/3 - based on review**
- [x] [FRQ 1](https://samayass.github.io/samayaCSA/markdown/2022/09/18/frq1.html)
- [x] [Deployment on AWS for team](https://csatri1.tk/)
- [x] [2D Arrays Hacks](https://samayass.github.io/samayaCSA/jupyter/2022/09/18/2d.html)
- [x] [2D Arrays Lesson](https://samayass.github.io/samayaCSA/jupyter/2022/09/19/2d-lesson.html)
- [x] [Agile Methodology]()
   - [Team Scrum Board](https://github.com/users/tangalice/projects/2)

**Comment by tangalice** [comment]
2.7 +

Score: 2.7+/3

  FRQ - Did 2019 FRQ Q1s + explained the code in comments of code
  Team Deployed Website
  2D Arrays hacks displayed horizontally 
  Agile Methodology demonstrated in team scrum board
