### ISSUE TITLE
Week 5 - Design Starters

### ISSUE THREAD

**Issue by samayass** [samayass/samayaCSA#7]
# [**My Fastpages**](https://samayass.github.io/samayaCSA/)
**Score: /3 - based on crossover grade
Score: /3 - based on review**
- [x] [Fibonacci](https://samayass.github.io/samayaCSA/jupyter/2022/09/24/fibonacci.html)
- [x] [Javascript](https://samayass.github.io/samayaCSA/jupyter/2022/09/25/JS.html)
- [x] [Wireframing + Design](https://sarayu-pr11.github.io/teamGrapeSnails/markdown/2022/09/23/pbl-plan.html)

**Comment by sarayu-pr11** [comment]
.9+/1: Fibonacci is all there and completed with effort; nice job!
.9+/1: Javascript arrays are interesting and thorough

1.8+/2
